FIX Prevent "Warning: Using a password on the command line interface can be insecure."

diff --git a/zabbix-mysql-dump b/zabbix-mysql-dump
--- a/zabbix-mysql-dump
+++ b/zabbix-mysql-dump
@@ -156,6 +156,9 @@ MYSQL_OPTS=()
 MYSQL_OPTS_BATCH=("${MYSQL_OPTS[@]}" --batch --silent)
 [ ! -z "$DBNAME" ] && MYSQL_OPTS_BATCH=("${MYSQL_OPTS_BATCH[@]}" -D $DBNAME)
 
+# Log file for errors
+ERRORLOG=$(mktemp)
+
 # Host name: try reverse lookup if IP is given
 DBHOSTNAME="$DBHOST"
 command -v dig >/dev/null 2>&1
@@ -222,8 +225,8 @@ fi
 #
 # Read table list from database
 [ "$QUIET" == "no" ] && echo "Fetching list of existing tables..."
-DB_TABLES=$(mysql "${MYSQL_OPTS_BATCH[@]}" -e "SELECT table_name FROM information_schema.tables WHERE table_schema = '$DBNAME'" 2>&1)
-if [ $? -ne 0 ]; then echo -e "ERROR while trying to access database:\n$DB_TABLES" 2>&1; exit 1; fi
+DB_TABLES=$(mysql "${MYSQL_OPTS_BATCH[@]}" -e "SELECT table_name FROM information_schema.tables WHERE table_schema = '$DBNAME'" 2>$ERRORLOG)
+if [ $? -ne 0 ]; then echo "ERROR while trying to access database:" 2>&1; cat $ERRORLOG 2>&1; exit 1; fi
 DB_TABLES=$(echo "$DB_TABLES" | sort)
 DB_TABLE_NUM=$(echo "$DB_TABLES" | wc -l)
 
@@ -262,7 +265,9 @@ while read table; do
 	mysqldump "${MYSQL_OPTS[@]}" \
 		--routines --opt --single-transaction --skip-lock-tables \
 		$dump_opt \
-		$DBNAME --tables ${table} >> "$DUMPFILE"
+		$DBNAME --tables ${table} >> "$DUMPFILE" 2>$ERRORLOG
+
+	if [ $? -ne 0 ]; then echo -e "\nERROR: Could not backup table ${table}:" >&2; cat $ERRORLOG >&2; exit 1; fi
 
 	if [ "$QUIET" == "no" ]; then
 		# show percentage
@@ -274,6 +279,8 @@ while read table; do
 		fi
 	fi
 done <<<"$DB_TABLES"
+
+rm $ERRORLOG
 
 #
 # COMPRESS BACKUP
