DOC Refreshed and corrected some docs and formatting

diff --git a/zabbix-mysql-dump b/zabbix-mysql-dump
--- a/zabbix-mysql-dump
+++ b/zabbix-mysql-dump
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # NAME
-#     zabbix-mysql-backupconf.sh - Configuration Backup for Zabbix 2.0 w/MySQL
+#     zabbix-mysql-dump - Configuration Backup for Zabbix with MySQL
 #
 # SYNOPSIS
 #     This is a MySQL configuration backup script for Zabbix 2.0, 2.2 or 2.4.
@@ -11,17 +11,20 @@
 #     The script is based on a script by Ricardo Santos
 #     (http://zabbixzone.com/zabbix/backuping-only-the-zabbix-configuration/)
 #
-#     Credits for some suggestions concerning the original script to:
+# CONTRIBUTORS
 #      - Ricardo Santos
+#      - Jens Berthold (maxhq)
 #      - Oleksiy Zagorskyi (zalex)
 #      - Petr Jendrejovsky
 #      - Jonathan Bayer
 #      - Andreas Niedermann (dre-)
 #      - Mișu Moldovan (dumol)
+#      - Daniel Schneller (dschneller)
 #
 # HISTORY
-#     0.7.2 (2015-04-07)
-#         ENH: Bash related fixes.
+#     0.7.2 (2016-01-22)
+#         ENH: Add quiet mode. IP reverse lookup optional (by Daniel Schneller)
+#         ENH: Bash related fixes (by Misu Moldovan)
 #
 #     0.7.1 (2015-01-27)
 #         NEW: Parsing of commandline arguments implemented
@@ -47,7 +50,7 @@
 #     0.2.0 (2011-11-05)
 #
 # AUTHOR
-#     Jens Berthold (maxhq), 2015
+#     Jens Berthold (maxhq), 2016
 
 
 #
@@ -72,17 +75,19 @@ USAGE
 	$(basename $BASH_SOURCE) [options]
 	
 OPTIONS
-	 -h host      - hostname/IP of MySQL server (default: $DBHOST)
-	 -d database  - Zabbix database name (default: $DBNAME)
-	 -u user      - MySQL user to access Zabbix database (default: $DBUSER)
-	 -p password  - MySQL user password (specify "-" for a prompt)
-	 -o outputdir - output directory for MySQL dump
-	                (default: $DUMPDIR) 
-         -q           - No output on succesful backup. For crontab use.
-         -n           - Skip reverse lookup of IP address for host.
+	-h host      - hostname/IP of MySQL server (default: $DBHOST)
+	-d database  - Zabbix database name (default: $DBNAME)
+	-u user      - MySQL user to access Zabbix database (default: $DBUSER)
+	-p password  - MySQL user password (specify "-" for a prompt)
+	-o outputdir - output directory for MySQL dump
+	               (default: $DUMPDIR) 
+	-q           - No output on succesful backup. For crontab use.
+	-n           - Skip reverse lookup of IP address for host.
+
 EXAMPLE
 	$(basename $BASH_SOURCE) -h 1.2.3.4 -d zabbixdb -u zabbix -p test
 	$(basename $BASH_SOURCE) -d zabbixdb -u zabbix -p - -o /tmp
+
 EOF
 	exit 1
 fi	
@@ -91,17 +96,17 @@ fi
 # PARSE COMMAND LINE ARGUMENTS
 #
 while getopts ":h:d:u:p:o:qn" opt; do
-  case $opt in
-    h)  DBHOST="$OPTARG" ;;
-    d)  DBNAME="$OPTARG" ;;
-    u)  DBUSER="$OPTARG" ;;
-    p)  DBPASS="$OPTARG" ;;
-    o)  DUMPDIR="$OPTARG" ;;
-    n)  REVERSELOOKUP="no" ;;
-    q)  QUIET="yes" ;;
-    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
-    :)  echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
-  esac
+	case $opt in
+		h)  DBHOST="$OPTARG" ;;
+		d)  DBNAME="$OPTARG" ;;
+		u)  DBUSER="$OPTARG" ;;
+		p)  DBPASS="$OPTARG" ;;
+		o)  DUMPDIR="$OPTARG" ;;
+		n)  REVERSELOOKUP="no" ;;
+		q)  QUIET="yes" ;;
+		\?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
+		:)  echo "Option -$OPTARG requires an argument" >&2; exit 1 ;;
+	esac
 done
 
 if [ "$DBPASS" = "" ]; then
@@ -117,22 +122,23 @@ fi
 #
 # CONSTANTS
 #
-MYSQL_CONN="-h ${DBHOST} -u ${DBUSER} -p${DBPASS} ${DBNAME}"
+MYSQL_CONN="-h $DBHOST -u $DBUSER -p$DBPASS $DBNAME"
 MYSQL_BATCH="mysql --batch --silent $MYSQL_CONN"
 
 DBHOSTNAME="$DBHOST"
-if [ "${REVERSELOOKUP}" == "yes" ]; then
+command -v dig >/dev/null 2>&1
+if [ "$REVERSELOOKUP" == "yes" ]; then
 	# Try resolving a given host ip
 	newHostname=$(dig +noall +answer -x $DBHOST | sed -r 's/((\S+)\s+)+([^\.]+)\..*/\3/')
 	test \! -z "$newHostname" && DBHOSTNAME="$newHostname"
 fi
 DUMPFILEBASE="zabbix_${DBHOSTNAME}_$(date +%Y%m%d-%H%M).sql"
-DUMPFILE="${DUMPDIR}/${DUMPFILEBASE}"
+DUMPFILE="$DUMPDIR/$DUMPFILEBASE"
 
 #
 # CONFIG DUMP
 #
-if [ "${QUIET}" == "no" ]; then
+if [ "$QUIET" == "no" ]; then
 	cat <<-EOF
 	Configuration:
 	 - host:     $DBHOST ($DBHOSTNAME)
@@ -183,7 +189,7 @@ fi
 mkdir -p "${DUMPDIR}"
 
 # Read table list from database
-[ "${QUIET}" == "no" ] && echo "Fetching list of existing tables..."
+[ "$QUIET" == "no" ] && echo "Fetching list of existing tables..."
 DB_TABLES=$($MYSQL_BATCH -e "SELECT table_name FROM information_schema.tables WHERE table_schema = '$DBNAME'" 2>&1)
 if [ $? -ne 0 ]; then echo -e "ERROR while trying to access database:\n$DB_TABLES" 2>&1; exit 1; fi
 DB_TABLES=$(echo "$DB_TABLES" | sort)
@@ -192,7 +198,7 @@ DB_TABLE_NUM=$(echo "$DB_TABLES" | wc -l)
 PROCESSED_DATA_TABLES=()
 i=0
 
-[ "${QUIET}" == "no" ] && echo "Starting table backups..."
+[ "$QUIET" == "no" ] && echo "Starting table backups..."
 while read table; do
 	# large data tables: only store schema
 	if elementIn "$table" "${DATA_TABLES[@]}"; then
@@ -202,9 +208,11 @@ while read table; do
 	else
 		dump_opt="--extended-insert=FALSE"
 	fi
+
 	mysqldump --routines --opt --single-transaction --skip-lock-tables \
-		$dump_opt $MYSQL_CONN --tables ${table} >>"${DUMPFILE}"
-	if [ "${QUIET}" == "no" ]; then
+		$dump_opt $MYSQL_CONN --tables ${table} >> "$DUMPFILE"
+
+	if [ "$QUIET" == "no" ]; then
 		# show percentage
 		i=$((i+1)); i_percent=$(($i * 100 / $DB_TABLE_NUM))
 		if [ $(($i_percent % 12)) -eq 0 ]; then
@@ -215,7 +223,10 @@ while read table; do
 	fi
 done <<<"$DB_TABLES" 
 
-if [ "${QUIET}" == "no" ]; then
+#
+# Compress backup file
+#
+if [ "$QUIET" == "no" ]; then
 	echo -e "\n"
 	echo "For the following large tables only the schema (without data) was stored:"
 	for table in "${PROCESSED_DATA_TABLES[@]}"; do echo " - $table"; done
@@ -223,13 +234,13 @@ if [ "${QUIET}" == "no" ]; then
 	echo 
 	echo "Compressing backup file..."
 fi
-gzip -f "${DUMPFILE}"
+gzip -f "$DUMPFILE"
 if [ $? -ne 0 ]; then
 	echo -e "\nERROR: Could not compress backup file, see previous messages" >&2
 	exit 1
 fi
 
-[ "${QUIET}" == "no" ] && echo -e "\nBackup Completed:\n${DUMPFILE}.gz"
+[ "$QUIET" == "no" ] && echo -e "\nBackup Completed:\n${DUMPFILE}.gz"
 
 exit 0
 
